name: frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**/*
  
  # Allow for manual triggers
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.FE_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.FE_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: './frontend/yarn.lock'

      - name: Build
        working-directory: './frontend'
        run: |
          yarn
          yarn build

      - name: Push into S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: frontend/dist
          bucket: cs3219-g29-fe
          bucket-region: ap-southeast-1
          dist-id: E2JDJSYJC8PSK8
