name: frontend

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - frontend/**/*

  # Allow for manual triggers
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/142948231110/locations/global/workloadIdentityPools/cs3219-g29-fe-pool/providers/cs3219-g29-fe-provider'
          service_account: 'cs3219-g29-fe@cs3219-362509.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        working-directory: './frontend'

      - name: 'Test deployment'
        run: 'curl https://cs3219-362509.et.r.appspot.com'
