name: frontend

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - frontend/**/*

  # Allow for manual triggers
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'checkout'
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/142948231110/locations/global/workloadIdentityPools/cs3219-g29-fe-pool/providers/cs3219-g29-fe-provider'
          service_account: 'cs3219-g29-fe@cs3219-362509.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: './frontend'

      # Check deployment outcome
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
